Repository woowacourse-teams/2024-pokerogue-helper, pull requests merged in 2024-08, with the labels that each got.

#113 [BE-REFACTOR] Log 상세화하여 추가적으로 찍기 및 핸들링 할 에러 추가
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/controller/ArticleController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/PokemonExceptionHandler.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
Labels: BE_REFACTOR 🌿

#119 [AN-FEAT] 꿀팁 웹뷰 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/tip/TipActivity.kt
  android/app/src/main/res/layout/activity_tip.xml
Labels: AN_FEAT ✨

#126 [AN-FEAT] 특성 ViewModel Test
  android/app/src/test/java/poke/rogue/helper/presentation/ability/AbilityViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
  android/testing/build.gradle.kts
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepository.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
Labels: AN_FEAT ✨

#116 [AN-REFACTOR] 상성 데이터 레이어 수정
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/MatchedTypesUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/res/drawable/icon_type_stellar.png
  android/app/src/test/java/poke/rogue/helper/presentation/type/TypeViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/DummyTypeData.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalTypeDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Type.kt
  android/data/src/main/java/poke/rogue/helper/data/model/TypeInfo.kt
  android/data/src/main/java/poke/rogue/helper/data/model/TypeMatchedTable.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeTypeRepository.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeTypeRepositoryTest.kt
Labels: AN_REFACTOR ✍️

#134 [BE-REFACTOR] PokemonType 쿼리 개선
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/PokemonTypeMatchingRepository.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/type/repository/PokemonTypeMatchingRepositoryTest.java
Labels: BE_REFACTOR 🌿

#131 [BE-REFACTOR] PokemonAbility 쿼리 개선
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
Labels: BE_REFACTOR 🌿

#137 [AN-REFACTOR] 앱바 중복 코드 분리 및 커스텀
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/toolbar/ToolbarActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/toolbar/ToolbarFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
  android/app/src/main/res/drawable/bg_search_view.xml
  android/app/src/main/res/drawable/ic_menu.xml
  android/app/src/main/res/drawable/icon_close.xml
  android/app/src/main/res/drawable/icon_search.xml
  android/app/src/main/res/layout/activity_ability.xml
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_pokemon.xml
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_ability.xml
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/layout/toolbar.xml
  android/app/src/main/res/menu/menu_toolbar.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
Labels: AN_UI 🎨, AN_REFACTOR ✍️

#140 [BE-REFACTOR] CI를 self-hosted runner로 변경
  .github/workflows/Backend-CD.yml
  .github/workflows/Backend-CI.yml
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
Labels: BE_INFRA 🚧

#132 [BE-REFACTOR] Batch Insert를 통한 성능 개선 #122
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
Labels: BE_REFACTOR 🌿

#148 [AN-Config] 테스트용 디바이스 추가
  android/app/build.gradle.kts
  android/stringmatcher/build.gradle.kts
Labels: AN_CONFIG 🧭

#157 [BE-FIX] 포켓몬 목록 조회 정렬 적용
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/repository/PokemonRepositoryTest.java
Labels: BE_FIX 🐛

#153 [BE-REFACTOR] NGINX limt_req 모듈 설정 변경
  backend/pokerogue/docker/fail2ban/jail.local
  backend/pokerogue/docker/nginx/conf.d/nginx.conf
  backend/pokerogue/src/test/java/com/pokerogue/helper/type/repository/PokemonTypeMatchingRepositoryTest.java
Labels: BE_INFRA 🚧

#151 [BE-REFACTOR] 내용이 없을 때 저장하는 값 수정
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/client/PokeClient.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/dto/Language.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/dto/Name.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/parser/DtoParser.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/PokemonTypeRepository.java
  backend/pokerogue/src/test/java/com/pokerogue/environment/client/FakePokeClient.java
Labels: BE_REFACTOR 🌿

#136 [AN-UI] 포켓몬 상세, 목록 화면의 타입 위치 수정
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PoketmonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultItemAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultItemViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/view/TypeChip.kt
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/app/src/main/res/layout/item_type.xml
  android/app/src/main/res/layout/item_type_name.xml
  android/app/src/main/res/layout/item_type_result.xml
Labels: AN_UI 🎨

#149 [AN-FEAT] Ability, Dex List InMemory 캐싱
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/PokemonListViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemotePokemonDetailDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemotePokemonListDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultPokemonDetailRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultPokemonListRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DexRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/PokemonDetailRepository.kt
  android/data/src/test/java/poke/rogue/helper/data/datasource/RemoteDexDataSourceTest.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakePokemonDetailRepository.kt
Labels: AN_FEAT ✨

#160 [AN-FEAT] 설문조사 링크 연결 및 Analytics 적용
  android/app/src/main/java/poke/rogue/helper/presentation/base/BindingFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/toolbar/ToolbarActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/toolbar/ToolbarFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/AnalyticsLoggerExtensions.kt
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/main/res/layout/item_type_selection.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
Labels: AN_FEAT ✨

#166 [AN-FIX] 베타 버전 배포 전 2차 QA 버그 수정
  android/app/src/androidTest/java/poke/rogue/helper/ExampleInstrumentedTest.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/res/drawable/img_tmp_loading.png
  android/app/src/main/res/drawable/temporal_small_round_electric_type.png
  android/app/src/main/res/drawable/temporal_small_round_normal_type.png
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/gradle/libs.versions.toml
Labels: AN_FIX 🐛

#174 [0.1.20-alpha/AN-FEAT] Click Event에 Throttle 처리
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/ViewInteractionUtils.kt
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/item_ability_description.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/app/src/main/res/layout/item_ability_title.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
Labels: AN_FEAT ✨

#177 [0.1.20-alpha/AN-FIX, AN-UI] 포켓몬 상세 화면 스탯 UI 색깔과 타입 UI
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel.kt
  android/app/src/main/res/drawable/progress_dex_stat.xml
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/item_stat.xml
  android/app/src/main/res/layout/item_type.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimensions.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
Labels: AN_FIX 🐛, AN_UI 🎨

#176 [0.1.20-alpha/AN-FIX] UI 이슈 사항 해결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailUiEventHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailNavigateHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/res/drawable/icon_add.xml
  android/app/src/main/res/drawable/icon_home.xml
  android/app/src/main/res/drawable/img_home_land_logo.png
  android/app/src/main/res/layout-land/activity_home.xml
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
Labels: AN_FIX 🐛, AN_UI 🎨

#175 [BE-FIX] 포켓몬이 없는 특성 상세 페이지 조회, 포켓몬 타입 정렬
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/domain/PokemonTest.java
Labels: BE_FIX 🐛, BE_REFACTOR 🌿

#178 [0.1.20-alpha/AN-UI] 상성 가로 화면 대응
  android/app/src/androidTest/java/poke/rogue/helper/presentation/type/TypeActivityTest.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionBottomSheetFragment.kt
  android/app/src/main/res/layout-land/activity_type.xml
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_type_selection_bottom_sheet.xml
Labels: AN_UI 🎨

#179 [0.1.20.alpha/AN-FEAT] 네트워크 ConnectException 및 HttpException Handling
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/error/ErrorViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/error/NetworkErrorActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/context/ContextExtension.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/ViewInteractionUtils.kt
  android/app/src/main/res/drawable/ic_network_error.xml
  android/app/src/main/res/layout/activity_network_error.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: AN_FEAT ✨

#181 [0.1.20-alpha/AN-UI, AN-FIX] 특성 description 의 줄 수를 조정한다
  android/app/src/main/java/poke/rogue/helper/presentation/ability/model/AbilityUiModel.kt
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/layout/item_ability_description.xml
Labels: AN_FIX 🐛, AN_UI 🎨

#180 [0.1.20-alpha/AN-UI, AN-FEAT] 포켓몬 이미지를 로딩 중에 progress indicator 를 보인다
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/ProgressListener.kt
  android/app/src/main/res/drawable/ic_ditto_silhouette.png
  android/app/src/main/res/drawable/ic_pikachu_silhouette.png
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
Labels: AN_FEAT ✨, AN_UI 🎨

#184 [0.1.2-alpha/AN-FEAT] Firebase Dev, Alpha 버전 로깅 툴 해제
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
Labels: AN_FEAT ✨

#186 [0.1.20-alpha/AN-FIX, AN_UI] 특성 상세 화면에서 포켓몬의 타입의 위치 변경
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FIX 🐛, AN_UI 🎨

#189 [0.1.3-alpha/AN-FIX] 홈화면 이동 기능 수정
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/res/layout-land/activity_type.xml
Labels: AN_FIX 🐛

#195 [0.1.30-alpha/AN-FIX, AN_UI] 포켓몬 디테일 화면 가로 화면 대응
  android/app/src/main/res/layout-land/fragment_pokemon_detail.xml
  android/gradle/libs.versions.toml
Labels: AN_FIX 🐛, AN_UI 🎨

#199 [BE] 3차 스프린트 CD 시연
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
Labels: BE_FIX 🐛

#204 [0.2.0.alpha/AN_UI] 홈 화면 메뉴 추가
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActionHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeNavigateEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/item/ItemActivity.kt
  android/app/src/main/res/drawable/icon_home_battle.png
  android/app/src/main/res/drawable/icon_home_biome.png
  android/app/src/main/res/drawable/icon_home_item.png
  android/app/src/main/res/layout/activity_biome.xml
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_item.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_UI 🎨

#205 [BE-INFRA] CI/CD 워크플로우 수정
  .github/workflows/Backend-CD.yml
  .github/workflows/Backend-CI.yml
Labels: BE_INFRA 🚧

#207 [0.2.0.alpha/AN-FEAT] remote ApiResponse 로 적용, BaseResponse 삭제, app 단 retrofit 의존성 걷어내기
  android/app/build.gradle.kts
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/error/ErrorViewModel.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/exception/ApiResponseExtensions.kt
  android/data/src/main/java/poke/rogue/helper/data/exception/PokeException.kt
  android/data/src/test/java/poke/rogue/helper/data/datasource/RemoteDexDataSourceTest.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/base/ApiResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/base/ApiResponseExtensions.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/PokeCall.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/PokeCallAdapterFactory.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/PokeConverterFactory.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/RetrofitModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/ServiceModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/AbilityService.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/PokeDexService.kt
  android/remote/src/test/java/poke/rogue/helper/remote/service/AbilityServiceTest.kt
  android/remote/src/test/java/poke/rogue/helper/remote/service/utils/ApiResponseAssertions.kt
  android/remote/src/test/java/poke/rogue/helper/remote/service/utils/ApiResponseExtensions.kt
  android/remote/src/test/java/poke/rogue/helper/remote/service/utils/FakeResponseUtils.kt
  android/remote/src/test/res/abilities.json
  android/remote/src/test/res/ability.json
Labels: AN_FEAT ✨

#209 [0.2.0.alpha/AN-FEAT, AN_UI] 포켓몬 상세 화면 Tab layout 틀
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailPagerAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonEvolutionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonInformationFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonMovesFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonStatFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/context/ContextExtension.kt
  android/app/src/main/res/drawable/tab_background.xml
  android/app/src/main/res/drawable/tab_background_selected.xml
  android/app/src/main/res/drawable/tab_background_unselected.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_evolution.xml
  android/app/src/main/res/layout/fragment_pokemon_information.xml
  android/app/src/main/res/layout/fragment_pokemon_moves.xml
  android/app/src/main/res/layout/fragment_pokemon_stat.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
Labels: AN_FEAT ✨, AN_UI 🎨

#208 [0.2.0.alpha/FEAT-AN] RemoteDataSource 에서 erro log 심기
  android/analytics/src/main/java/poke/rogue/helper/analytics/AnalyticsLogger.kt
  android/data/build.gradle.kts
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteDexDataSource.kt
  android/data/src/test/java/poke/rogue/helper/data/datasource/RemoteDexDataSourceTest.kt
Labels: AN_FEAT ✨

#214 [0.2.0.alpha/AN_UI] 바이옴 리스트 화면 추가
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeUiEventHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/model/BiomeUiModel.kt
  android/app/src/main/res/layout/activity_biome.xml
  android/app/src/main/res/layout/activity_biome_detail.xml
  android/app/src/main/res/layout/item_biome.xml
Labels: AN_UI 🎨

#212 [0.2.0.alpha/AN-FEAT] 네트워크 ReConnection 시 Refresh
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/ErrorEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/ErrorHandleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/ErrorHandleFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/ErrorHandleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/NetworkErrorActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/toolbar/ToolbarActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/toolbar/ToolbarFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/item/ItemActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/event/EventFlow.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/event/RefreshEventBus.kt
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨

#225 [2.0.0-alph/AN-UI,Fix] 화면 나갔다가 5초 이후에 들어오면 오둥이 보이는 버그 수정 + clearFocus
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/NetworkErrorActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/activity/ActivityExtension.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/event/EventFlow.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/event/RefreshEventBus.kt
  android/app/src/main/res/layout/activity_pokemon.xml
  android/app/src/main/res/layout/activity_pokemon_list.xml
  android/app/src/test/java/poke/rogue/helper/presentation/util/event/EventFlowTest.kt
Labels: AN_FIX 🐛, AN_UI 🎨

#232 [2.0.0.alpha/AN-UI] 배틀 도우미 화면 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/WeatherSpinnerAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/WeatherUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/res/drawable/bg_battle_selection.xml
  android/app/src/main/res/drawable/bg_spinner.xml
  android/app/src/main/res/drawable/icon_air.xml
  android/app/src/main/res/drawable/icon_arena.xml
  android/app/src/main/res/drawable/icon_arrow_down.xml
  android/app/src/main/res/drawable/icon_arrow_right.xml
  android/app/src/main/res/drawable/icon_foggy.xml
  android/app/src/main/res/drawable/icon_hail.xml
  android/app/src/main/res/drawable/icon_pokemon_selection_mine.png
  android/app/src/main/res/drawable/icon_pokemon_selection_op.png
  android/app/src/main/res/drawable/icon_rain.xml
  android/app/src/main/res/drawable/icon_snow.xml
  android/app/src/main/res/drawable/icon_sun.xml
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/item_spinner_weather.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
Labels: AN_UI 🎨

#222 [BE-FEAT] 배틀 날씨 리스트 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/DataInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/Weather.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/WeatherRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/WeatherResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/data/weather.txt
  backend/pokerogue/src/test/java/com/pokerogue/helper/battle/DataInitializerTest.java
Labels: BE_FEAT ✨

#228 [0.2.0.alpha/AN-FEAT] Pokemon FIlter, Sort data 로직
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonFilter.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonGeneration.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonSort.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DexRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeDexRepositoryTest.kt
Labels: AN_FEAT ✨

#248 [BE-FIX] 기술 리스트에서 카테고리 로고 이미지 누락
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
Labels: BE_FIX 🐛

#242 [0.2.0.alpha/AN_FEAT_UI] PokemonList Filter, PokeChip, PokeChipGroup Component 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeFilterUiEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeFilterUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeFilterUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeFilterViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeGenerationUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokemonFilterBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/SelectableUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/DimensionUtils.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/ViewInteractionUtils.kt
  android/app/src/main/java/poke/rogue/helper/ui/component/PokeChip.kt
  android/app/src/main/java/poke/rogue/helper/ui/component/PokeChipGroup.kt
  android/app/src/main/java/poke/rogue/helper/ui/layout/PaddingValues.kt
  android/app/src/main/res/drawable/bg_battle_selection.xml
  android/app/src/main/res/drawable/ic_filter.xml
  android/app/src/main/res/layout/activity_pokemon_list.xml
  android/app/src/main/res/layout/bottom_sheet_pokemon_filter.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/PokemonListViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
Labels: AN_FEAT ✨, AN_UI 🎨

#254 [0.2.0.alpha/AN_FEAT] PokemonList Sort Chip 구현, Sort BottomSheet 구현
  .github/workflows/Android_PR_Builder.yml
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeFilterUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokeFilterViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/PokemonFilterBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/SelectableUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokeSortAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokeSortViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokemonSortBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokemonSortHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokemonSortUiModel.kt
  android/app/src/main/res/drawable/ic_check_24.xml
  android/app/src/main/res/drawable/ic_sort.xml
  android/app/src/main/res/layout/activity_pokemon_list.xml
  android/app/src/main/res/layout/bottom_sheet_pokemon_filter.xml
  android/app/src/main/res/layout/bottom_sheet_pokemon_sort.xml
  android/app/src/main/res/layout/item_pokemon_sort.xml
  android/app/src/main/res/values/strings.xml
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
Labels: AN_FEAT ✨

#256 [0.2.0.alpha/AN_FEAT] 바이옴 네트워크 연결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonInformationFragment.kt
  android/app/src/main/res/layout/item_biome_map.xml
  android/app/src/main/res/layout/item_pokemon_detail_information_biome.xml
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteBiomeDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Biome.kt
  android/data/src/main/java/poke/rogue/helper/data/model/BiomeDetail.kt
  android/data/src/main/java/poke/rogue/helper/data/model/BiomeNextBiome.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonBiome.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
  android/data/src/main/java/poke/rogue/helper/data/model/biome/BiomePokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/biome/BossPokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/biome/GymPokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/biome/WildPokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BiomeRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/biomes/BiomeDetailResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/biomes/BiomesResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/ServiceModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/BiomeService.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepositoryTest.kt
Labels: AN_FEAT ✨

#257 [0.2.0.alpha/AN_FEAT, AN_UI] 포켓몬 상세 화면에서 진화 정보
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/EvolutionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/EvolutionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionViewGroup.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/EvolutionsUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/SingleEvolutionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/NestedScrollableHost.kt
  android/app/src/main/res/drawable/tab_border_background.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_evolution.xml
  android/app/src/main/res/layout/item_pokemon_detail_evolution.xml
  android/app/src/main/res/layout/view_group_pokemon_evolution.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/model/EvolutionsUiModelTest.kt
Labels: AN_FEAT ✨, AN_UI 🎨

#262 [0.2.0.alpha/AN-FEAT] PokeList Room Cache, Splash 화면, Pokemon Api v2 서버 연결
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/error/ErrorHandleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokeSortViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokemonSortUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/splash/PokemonIntroActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/splash/PokemonIntroViewModel.kt
  android/app/src/main/res/drawable/icon_type_dragon.png
  android/app/src/main/res/drawable/icon_type_dragon.xml
  android/app/src/main/res/drawable/icon_type_ground.png
  android/app/src/main/res/drawable/icon_type_ground.xml
  android/app/src/main/res/drawable/icon_type_psychic.png
  android/app/src/main/res/drawable/icon_type_psychic.xml
  android/app/src/main/res/drawable/icon_type_rock.png
  android/app/src/main/res/drawable/icon_type_rock.xml
  android/app/src/main/res/drawable/icon_type_unknown.png
  android/app/src/main/res/layout/activity_pokemon_intro.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/splash.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/PokemonListViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Type.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DexRepository.kt
  android/local/build.gradle.kts
  android/local/src/androidTest/java/poke/rogue/helper/local/dao/PokemonDaoTest.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/entity/PokemonFixtures.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/utils/ContextUtils.kt
  android/local/src/main/java/poke/rogue/helper/local/converter/PokemonTypeConverters.kt
  android/local/src/main/java/poke/rogue/helper/local/dao/PokemonDao.kt
  android/local/src/main/java/poke/rogue/helper/local/db/.gitkeep
  android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt
  android/local/src/main/java/poke/rogue/helper/local/entity/.gitkeep
  android/local/src/main/java/poke/rogue/helper/local/entity/PokemonEntity.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonResponse2.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/RetrofitModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/PokeDexService.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
Labels: AN_FEAT ✨

#268 [BE-REFACTOR] 기술 리스트에 타입과 카테고리 영어 이름 포함
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/MoveCategory.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/MoveResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/Type.java
Labels: BE_REFACTOR 🌿

#279 [0.2.0.alpha/AN_FEAT] 배틀 도우미 API 연결
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleResultUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleSelectionsState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/BattlePredictionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/BattleResultUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/PokemonSelectionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SkillSelectionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/WeatherUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionDataUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/QueryHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/SelectableUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/SelectionBindingAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/SelectableUiModel.kt
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/activity_battle_selection.xml
  android/app/src/main/res/layout/fragment_pokemon_selection.xml
  android/app/src/main/res/layout/fragment_skill_selection.xml
  android/app/src/main/res/layout/item_battle_skill_selection.xml
  android/app/src/main/res/values/strings.xml
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteBattleDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/model/BattlePrediction.kt
  android/data/src/main/java/poke/rogue/helper/data/model/BattleSkill.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Weather.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/battle/BattlePredictionResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/battle/PokemonSkillResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/battle/WeatherResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/ServiceModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/BattleService.kt
Labels: AN_FEAT ✨

#277 [BE-REFACTOR] 배틀 관련 empty 데이터 처리
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/DataInitializer.java
Labels: BE_REFACTOR 🌿

#281 [0.2.0.alpha/AN_FEAT] 포켓몬 상세 서버 연결, 바이옴 <-> 포켓몬 상세 이동
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomePokemonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailNavigateHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/EvolutionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/EvolutionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonInformationFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/skill/PokemonDetailSkillFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/stat/AbilityTitleAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/stat/AbilityTitleViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/stat/PokemonStatFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/AbilityTitleUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/EvolutionsUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonSkillUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/SingleEvolutionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/SkillCategoryUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel.kt
  android/app/src/main/java/poke/rogue/helper/ui/component/PokeChip.kt
  android/app/src/main/res/drawable/bg_ability_title.xml
  android/app/src/main/res/layout/fragment_pokemon_skills.xml
  android/app/src/main/res/layout/item_ability_title.xml
  android/app/src/main/res/layout/item_pokemon_detail_evolution.xml
  android/app/src/main/res/layout/item_pokemon_detail_skill.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Evolution.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonBiome.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonDetailAbility.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonSkill.kt
  android/data/src/main/java/poke/rogue/helper/data/model/SkillCategory.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Stat.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/ability/PokemonAbilityResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/biom/PokemonBiomeResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/EvolutionResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonDetailResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonSkillResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/PokeDexService.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
Labels: AN_FEAT ✨

#288 [1.0.1/AN_FEAT] 배틀 페이지 뒷모습 이미지 추가
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/PokemonSelectionUiModel.kt
  android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
  android/data/src/test/java/poke/rogue/helper/data/model/PokemonMapperTest.kt
  android/data/src/test/java/poke/rogue/helper/data/model/fixture/PokemonResponseFixture.kt
  android/local/src/main/java/poke/rogue/helper/local/entity/PokemonEntity.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
Labels: AN_FEAT ✨

#294 [BE-FIX] 배틀 결과 계산에서 날씨 배수 조건 추가
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleMove.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
Labels: BE_FEAT ✨

#295 [1.0.1/AN_FIX] 포켓몬 상세 이미지와 진화 UI
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionViewGroup.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonSkillUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_evolution.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/app/src/main/res/layout/item_pokemon_detail_evolution.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
Labels: AN_FEAT ✨, AN_UI 🎨
