Repository woowacourse-teams/2024-pokerogue-helper, pull requests merged in 2024-07, with the labels that each got.

#14 [AN-UI] 안드로이드 공통 디자인 컴포넌트 세팅
  android/app/src/main/java/poke/rogue/helper/presentation/type/.gitkeep
  android/app/src/main/java/poke/rogue/helper/presentation/type/PokeParallelogramLayout.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/DimensionUtils.kt
  android/app/src/main/res/drawable/ic_arrow_back_24.xml
  android/app/src/main/res/drawable/ic_menu.xml
  android/app/src/main/res/drawable/ic_type_delete.xml
  android/app/src/main/res/drawable/ic_type_reset.xml
  android/app/src/main/res/drawable/icon_type_bug.png
  android/app/src/main/res/drawable/icon_type_dark.png
  android/app/src/main/res/drawable/icon_type_dragon.png
  android/app/src/main/res/drawable/icon_type_electric.png
  android/app/src/main/res/drawable/icon_type_fairy.png
  android/app/src/main/res/drawable/icon_type_fighting.png
  android/app/src/main/res/drawable/icon_type_fire.png
  android/app/src/main/res/drawable/icon_type_flying.png
  android/app/src/main/res/drawable/icon_type_ghost.png
  android/app/src/main/res/drawable/icon_type_green.png
  android/app/src/main/res/drawable/icon_type_ground.png
  android/app/src/main/res/drawable/icon_type_ice.png
  android/app/src/main/res/drawable/icon_type_normal.png
  android/app/src/main/res/drawable/icon_type_poison.png
  android/app/src/main/res/drawable/icon_type_psychic.png
  android/app/src/main/res/drawable/icon_type_rock.png
  android/app/src/main/res/drawable/icon_type_steel.png
  android/app/src/main/res/drawable/icon_type_water.png
  android/app/src/main/res/font/poke_font.xml
  android/app/src/main/res/font/pretendard_medium.otf
  android/app/src/main/res/font/pretendard_semibold.otf
  android/app/src/main/res/values-v28/type.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/main/res/values/type.xml
Labels: AN_UI

#16 [BE-FEAT] 꿀팁 리스트 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/controller/ArticleController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/domain/Article.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/dto/ArticleResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/repository/ArticleRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/service/ArticleService.java
Labels: BE_FEAT

#8 [AN-UI] 상성 페이지 UI 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/data/mapper/.gitkeep
  android/app/src/main/java/poke/rogue/helper/data/model/.gitkeep
  android/app/src/main/java/poke/rogue/helper/data/model/MatchedResult.kt
  android/app/src/main/java/poke/rogue/helper/data/model/TypeInfo.kt
  android/app/src/main/java/poke/rogue/helper/local/dao/TypeDao.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultView.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/TypeMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/TypeMatchedResultMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeMatchedResultUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/view/PokeParallelogramLayout.kt
  android/app/src/main/res/drawable/bg_type_choice.xml
  android/app/src/main/res/drawable/bg_type_choice_bottom_sheet.xml
  android/app/src/main/res/drawable/img_property_tmp_1.png
  android/app/src/main/res/drawable/img_property_tmp_2.png
  android/app/src/main/res/drawable/img_type_tmp_1.png
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_type_choice_bottom_sheet.xml
  android/app/src/main/res/layout/item_type_choice.xml
  android/app/src/main/res/layout/item_type_name.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
  android/app/src/main/res/values/themes.xml
Labels: AN_UI

#11 [AN-UI] 홈 화면 UI 구현
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/res/drawable/ic_toolbar_back.xml
  android/app/src/main/res/drawable/ic_toolbar_nav.xml
  android/app/src/main/res/drawable/img_home_ability.png
  android/app/src/main/res/drawable/img_home_dex.png
  android/app/src/main/res/drawable/img_home_logo.png
  android/app/src/main/res/drawable/img_home_temp1.png
  android/app/src/main/res/drawable/img_home_tip.png
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/toolbar.xml
  android/app/src/main/res/menu/menu_toolbar.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
Labels: AN_UI

#20 [BE_FEAT] 단일 포켓몬 정보 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/GlobalCustomException.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/PokemonExceptionHandler.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
Labels: BE_FEAT

#22 [AN-FEAT] 해커톤용 포켓몬 도감 UI/Presentation 로직
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/base/BindingFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon/.gitkeep
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokeMonItemClickListener.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonStatAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonTypeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PoketmonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/PokemonDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/Stat.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/TypeMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/LinearSpacingItemDecoration.kt
  android/app/src/main/res/drawable/ic_menu.xml
  android/app/src/main/res/drawable/ic_toolbar_back.xml
  android/app/src/main/res/drawable/ic_toolbar_nav.xml
  android/app/src/main/res/drawable/icon_error.xml
  android/app/src/main/res/drawable/icon_poke.xml
  android/app/src/main/res/drawable/progress_dex_stat.xml
  android/app/src/main/res/drawable/shape_grey_80_fill_20_rect.xml
  android/app/src/main/res/drawable/shape_pokemon_corner_radius.xml
  android/app/src/main/res/drawable/temporal_small_round_electric_type.png
  android/app/src/main/res/drawable/temporal_small_round_normal_type.png
  android/app/src/main/res/layout/activity_pokemon.xml
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/app/src/main/res/layout/item_stat.xml
  android/app/src/main/res/layout/item_type_right_name.xml
  android/app/src/main/res/layout/toolbar.xml
  android/app/src/main/res/menu/menu_pokemon_list_pokemon_search.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
Labels: AN_FEAT

#33 [AN-UI] 포켓몬 상성 Icon + TextAppearance 추가
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/res/drawable/icon_type_bug.png
  android/app/src/main/res/drawable/icon_type_bug.xml
  android/app/src/main/res/drawable/icon_type_dark.png
  android/app/src/main/res/drawable/icon_type_dark.xml
  android/app/src/main/res/drawable/icon_type_dragon.png
  android/app/src/main/res/drawable/icon_type_dragon.xml
  android/app/src/main/res/drawable/icon_type_electric.png
  android/app/src/main/res/drawable/icon_type_electric.xml
  android/app/src/main/res/drawable/icon_type_fairy.png
  android/app/src/main/res/drawable/icon_type_fairy.xml
  android/app/src/main/res/drawable/icon_type_fighting.png
  android/app/src/main/res/drawable/icon_type_fighting.xml
  android/app/src/main/res/drawable/icon_type_fire.png
  android/app/src/main/res/drawable/icon_type_fire.xml
  android/app/src/main/res/drawable/icon_type_flying.png
  android/app/src/main/res/drawable/icon_type_flying.xml
  android/app/src/main/res/drawable/icon_type_ghost.png
  android/app/src/main/res/drawable/icon_type_ghost.xml
  android/app/src/main/res/drawable/icon_type_grass.xml
  android/app/src/main/res/drawable/icon_type_green.png
  android/app/src/main/res/drawable/icon_type_ground.png
  android/app/src/main/res/drawable/icon_type_ground.xml
  android/app/src/main/res/drawable/icon_type_ice.png
  android/app/src/main/res/drawable/icon_type_ice.xml
  android/app/src/main/res/drawable/icon_type_normal.png
  android/app/src/main/res/drawable/icon_type_normal.xml
  android/app/src/main/res/drawable/icon_type_poison.png
  android/app/src/main/res/drawable/icon_type_poison.xml
  android/app/src/main/res/drawable/icon_type_psychic.png
  android/app/src/main/res/drawable/icon_type_psychic.xml
  android/app/src/main/res/drawable/icon_type_rock.png
  android/app/src/main/res/drawable/icon_type_rock.xml
  android/app/src/main/res/drawable/icon_type_steel.png
  android/app/src/main/res/drawable/icon_type_steel.xml
  android/app/src/main/res/drawable/icon_type_water.png
  android/app/src/main/res/drawable/icon_type_water.xml
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/toolbar.xml
  android/app/src/main/res/values-v28/type.xml
  android/app/src/main/res/values/type.xml
Labels: AN_UI

#34 [AN-FEAT] Network Config 추가
  .github/workflows/Android_PR_Builder.yml
  android/app/build.gradle.kts
  android/app/src/main/java/poke/rogue/helper/remote/RetrofitModule.kt
  android/app/src/main/java/poke/rogue/helper/remote/ServiceModule.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/.gitkeep
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/BaseResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityDetailResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/poke/PokemonDetailResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/poke/PokemonResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/type/PokemonTypeResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/service/.gitkeep
  android/app/src/main/java/poke/rogue/helper/remote/service/AbilityService.kt
  android/app/src/main/java/poke/rogue/helper/remote/service/PokeDexService.kt
Labels: AN_FEAT

#42 [BE-FEAT] 수정 요청 사항 반영
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonTypeMapping.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
Labels: BE_FEAT

#46 [BE-FEAT] 개발 DB 초기 데이터 삽입
  .github/workflows/Backend-CD.yml
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonTypeMapping.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonAbilityMappingRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonTypeMappingRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/PokemonType.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/PokemonTypeRepository.java
Labels: BE_FEAT ✨

#36 [AN-REFACTOR] 포켓몬 도감 데이터는 데이터 레이어에서 불러온다.
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/data/datasource/FakePokemonDetailDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/datasource/FakePokemonListDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
  android/app/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Stat.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Type.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/FakePokemonDetailRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/FakePokemonListRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/PokemonDetailRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/PokemonListRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokeMonItemClickListener.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonStatAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PoketmonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonDetailUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/PokemonDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/poketmon2/detail/Stat.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/res/layout/activity_pokemon.xml
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/app/src/main/res/layout/item_stat.xml
Labels: AN_REFACTOR ✍️

#47 [AN_UI] TypeChip component, CommonBindingAdapter, Serializable, Parcelable Util 함수들 추가
  android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/view/TypeChip.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/BundleExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/IntentExensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/layout/item_type.xml
  android/app/src/main/res/layout/item_type_name.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/type.xml
Labels: AN_UI 🎨

#38 [AN-REFACTOR] 상성 화면 리팩토링
  android/app/src/main/java/poke/rogue/helper/data/datasource/LocalTypeDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/MatchedTypes.kt
  android/app/src/main/java/poke/rogue/helper/data/model/TypeMatchedResult.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/TypeRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/TypeMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/TypeMatchedResultMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/MatchedTypesUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeSelectionUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultItemAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultItemViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/view/PokeParallelogramLayout.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/view/TypeResultView.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/Event.kt
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_type_choice_bottom_sheet.xml
  android/app/src/main/res/layout/item_type_choice.xml
  android/app/src/main/res/layout/item_type_parallelogram.xml
  android/app/src/main/res/layout/item_type_result.xml
Labels: AN_REFACTOR ✍️

#55 [BE-FEAT] 타입 리스트를 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/controller/PokemonTypeController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
Labels: BE_FEAT ✨

#57 [BE-FEAT] 단일 꿀팁 상세 정보를 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/controller/ArticleController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/dto/ArticleDetailsResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/article/service/ArticleService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java
Labels: BE_FEAT ✨

#59 [AN_REFACTOR] 홈 화면 MVVM 패턴 적용
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActionHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeNavigateEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeViewModel.kt
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/toolbar.xml
  android/app/src/main/res/values/style.xml
Labels: AN_REFACTOR ✍️

#60 [AN_UI] 포켓몬 도감 목록에서 포켓몬 이름을 통해 검색
  android/app/src/main/java/poke/rogue/helper/data/datasource/FakePokemonListDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/FakePokemonListRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/PokemonListRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokeMonItemClickListener.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonDetailNavigateHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonQueryHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PoketmonViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/SearchViewBindingAdapter.kt
  android/app/src/main/res/drawable/rounded_searchbar_background.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨, AN_UI 🎨

#67 [AN_REFACTOR] 특성 화면 MVVM 패턴 적용
  android/app/src/main/java/poke/rogue/helper/presentation/ability/.gitkeep
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityUiEventHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewModel.kt
  android/app/src/main/res/layout/activity_ability.xml
  android/app/src/main/res/layout/item_ability_description.xml
Labels: AN_REFACTOR ✍️

#61 [BE-FEAT] 단일 특성 정보를 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityWithPokemonsResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/SameAbilityPokemonResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
Labels: BE_FEAT ✨

#65 [AN-FEAT] 포켓몬 목록를 네트워크를 통해 로드
  android/app/src/main/java/poke/rogue/helper/data/datasource/RemotePokemonListDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Type.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/DefaultPokemonListRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/PokemonListRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityDetailResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonDetailResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/type/PokemonTypeResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/service/PokeDexService.kt
  android/app/src/test/java/poke/rogue/helper/data/datasource/FakePokemonListDataSource.kt
  android/app/src/test/java/poke/rogue/helper/data/datasource/RemotePokemonListDataSourceTest.kt
  android/app/src/test/java/poke/rogue/helper/data/repository/FakePokemonListRepository.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/PokemonListViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonResponseTest.kt
  android/app/src/test/java/poke/rogue/helper/remote/dto/response/type/PokemonTypeResponseTest.kt
  android/app/src/test/java/poke/rogue/helper/utils/fixture/PokemonTestFixture.kt
  android/app/src/test/java/poke/rogue/helper/utils/fixture/TypeTestFixture.kt
Labels: AN_FEAT ✨

#73 [BE-FEAT] 타입 상성 리스트를 불러오는 API
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/controller/PokemonTypeController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonMatchingAndTypeResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonMatchingResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
Labels: BE_FEAT ✨

#75 [BE-FIX] 단일 특성 조회 API 쿼리문 수정
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
Labels: BE_FIX 🐛

#76 [BE-FEAT] 1차 배포 대비 수정사항 반영
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/dto/pokemon/PokemonDetail.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/parser/DtoParser.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
  backend/pokerogue/src/main/java/com/pokerogue/external/s3/service/S3Service.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/PokemonAbilityWithPokemonsResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/SameAbilityPokemonResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
Labels: BE_FEAT ✨

#80 [BE-FEAT] 1차 배포 대비 수정사항 반영
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/parser/DtoParser.java
  backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
Labels: BE_FEAT ✨

#78 [AN-FEAT] 특성 목록 네트워크 연결
  android/app/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Ability.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/AbilityRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/model/AbilityUiModel.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/service/AbilityService.kt
  android/app/src/main/res/layout/activity_ability_detail.xml
  android/app/src/main/res/layout/item_ability_description.xml
Labels: AN_FEAT ✨

#85 [BE-FEAT] 1차 배포 대비 수정사항 반영
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/PokemonAbilityMapping.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokedexResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/PokemonServiceTest.java
Labels: BE_FEAT ✨

#81 [AN-FEAT] 포켓몬 상세 데이터를 네트워크를 통해 로드
  android/app/src/main/java/poke/rogue/helper/data/datasource/RemotePokemonDetailDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/DefaultPokemonDetailRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/PokemonDetailRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonDetailUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonDetailResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/service/PokeDexService.kt
  android/app/src/main/res/layout/fragment_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_list.xml
  android/app/src/test/java/poke/rogue/helper/data/datasource/FakePokemonDetailDataSource.kt
  android/app/src/test/java/poke/rogue/helper/data/repository/FakePokemonDetailRepository.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
Labels: AN_FEAT ✨

#69 [AN-FEAT] 상성 화면 세부적인 기능 수정 및 추가
  android/app/src/main/java/poke/rogue/helper/data/datasource/LocalTypeDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/MatchedResult.kt
  android/app/src/main/java/poke/rogue/helper/data/model/MatchedTypes.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Type.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/TypeRepository.kt
  android/app/src/main/java/poke/rogue/helper/local/DummyTypeData.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/MatchedResultMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/TypeMatchedResultMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/MatchedTypesUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionBottomSheetFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/drawable/bg_type_choice_container.xml
  android/app/src/main/res/drawable/bg_type_selection_bottom_sheet.xml
  android/app/src/main/res/drawable/bg_type_selection_item.xml
  android/app/src/main/res/drawable/img_property_tmp_1.png
  android/app/src/main/res/drawable/img_type_empty_view_placeholder.xml
  android/app/src/main/res/drawable/img_type_tmp_1.png
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_type_selection_bottom_sheet.xml
  android/app/src/main/res/layout/item_type_choice.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/main/res/layout/item_type_selection.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
  android/app/src/test/java/poke/rogue/helper/presentation/type/TypeViewModelTest.kt
Labels: AN_FEAT ✨, AN_REFACTOR ✍️

#93 [AN-CONFIG] 개발 서버 다운시 Local host 로 리다이렉션
  .github/workflows/Android_PR_Builder.yml
  .gitignore
  android/.gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/remote/RetrofitModule.kt
  android/app/src/main/java/poke/rogue/helper/remote/interceptor/RedirectInterceptor.kt
  android/app/src/main/res/xml/network_security_config.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
Labels: AN_CONFIG 🧭

#89 [BE-FEAT] Nginx keepalive, log 설정 변경
  .github/workflows/Backend-CD.yml
  backend/pokerogue/docker/nginx/conf.d/nginx.conf
Labels: BE_FEAT ✨, BE_FIX 🐛

#97 [AN_CI] PR Open 될 때 reviewers, assignees, labels 자동 할당
  .github/actions/add_labels/action.yml
  .github/actions/reviewers.yml
  .github/workflows/Android_PR_Builder.yml
Labels: AN_CI/CD 🤖

#96 [AN-FEAT] 특성 상세 네트워크 연결
  android/app/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/app/src/main/java/poke/rogue/helper/data/model/Ability.kt
  android/app/src/main/java/poke/rogue/helper/data/model/AbilityDetail.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/AbilityRepository.kt
  android/app/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailUiEventHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/type/AbilityDetailTypeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/model/AbilityDetailUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/model/AbilityUiModel.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityDetailResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/dto/response/ability/AbilityResponse.kt
  android/app/src/main/java/poke/rogue/helper/remote/service/AbilityService.kt
  android/app/src/main/res/layout/activity_ability_detail.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨, AN_REFACTOR ✍️

#109 [AN-REFACTOR] 특성 상세 페이지 Fragment로 마이그레이션
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
  android/app/src/main/res/layout/activity_ability.xml
  android/app/src/main/res/layout/fragment_ability.xml
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_REFACTOR ✍️

#106 [AN-UI] 타입 화면 수정 사항 반영
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/MatchedResultMapper.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/MatchedResultUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/MatchedTypesUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionAdapter.kt
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/item_type.xml
  android/app/src/main/res/layout/item_type_name.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/test/java/poke/rogue/helper/presentation/type/TypeViewModelTest.kt
Labels: AN_UI 🎨

#111 [AN_FEAT] 포켓몬, 특성 초성 검색
  android/data/build.gradle.kts
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemotePokemonListDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultPokemonListRepository.kt
  android/data/src/test/java/poke/rogue/helper/data/datasource/RemotePokemonListDataSourceTest.kt
  android/settings.gradle.kts
  android/stringmatcher/.gitignore
  android/stringmatcher/build.gradle.kts
  android/stringmatcher/src/main/java/poke/rogue/helper/stringmatcher/KrStringMatcher.kt
  android/stringmatcher/src/main/java/poke/rogue/helper/stringmatcher/StringMatcher.kt
  android/stringmatcher/src/main/java/poke/rogue/helper/stringmatcher/util/StringExtentions.kt
  android/stringmatcher/src/test/java/poke/rogue/helper/stringmatcher/KrStringMatcherTest.kt
Labels: AN_FEAT ✨

#117 [BE-INFRA] 무작위 네트워크 공격 방지를 위한 fail2ban 추가
  .github/workflows/Backend-CD.yml
  backend/pokerogue/docker/Dockerfile-fail2ban
  backend/pokerogue/docker/Dockerfile-nginx
  backend/pokerogue/docker/fail2ban/jail.local
  backend/pokerogue/docker/fail2ban/paths-common.conf
  backend/pokerogue/docker/nginx/conf.d/nginx.conf
  backend/pokerogue/docker/nginx/nginx.conf
Labels: BE_INFRA 🚧
