Repository woowacourse-teams/2024-pokerogue-helper, pull requests merged in 2024-12, with the labels that each got.

#462 [1.2.0/AN-FEAT] 기본 문자열 리소스 영어로
  android/app/src/main/java/poke/rogue/helper/presentation/battle/WeatherSpinnerAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SkillSelectionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/sort/PokemonSortUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/SpannableStringExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/drawable-ko-rKR/img_type_empty_view_placeholder.xml
  android/app/src/main/res/drawable/icon_type_fighting.xml
  android/app/src/main/res/drawable/img_type_empty_view_placeholder.xml
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/activity_type.xml
  android/app/src/main/res/layout/fragment_pokemon_skills.xml
  android/app/src/main/res/layout/item_biome.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/main/res/values-ko-rKR/strings.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/home/HomeActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/util/SpannableStringExtensionsKtTest.kt
Labels: AN_FEAT ✨, v1.2.0 🏷️

#464 [1.2.0/AN-UI, AN-FEAT] 특성 목록 스크롤 시 앱 바 애니메이션 적용
  android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/layout/fragment_ability.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/util/SpannableStringExtensionsKtTest.kt
Labels: AN_FEAT ✨, AN_UI 🎨, v1.2.0 🏷️

#466 [1.2.0/AN-UI, AN-FEAT] 특성 디테일 스크롤 시 앱 바 애니메이션 적용
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/CommonBindingAdapter.kt
  android/app/src/main/res/layout-land/fragment_ability_detail.xml
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/values-ko-rKR/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨, AN_UI 🎨, v1.2.0 🏷️

#472 [1.2.0/AN-UI] 포켓몬 리스트 스크롤 시 Appbar, PokeChips Collapse 애니메이션 적용
  android/app/src/main/res/layout/activity_pokemon_list.xml
Labels: AN_UI 🎨, v1.2.0 🏷️

#483 [1.2.0AN-FIX] 포켓몬 상세의 진화 정보에서 동일한 포켓몬 클릭 시 토스트 메시지
  android/app/src/main/java/poke/rogue/helper/presentation/dex/AnalyticsExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/NavigateToBattleEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/res/values-ko-rKR/strings.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
Labels: AN_FIX 🐛, v1.2.0 🏷️

#476 [1.2.0/AN-UI] PokemonList 스크롤 최상단으로 올리는 버튼
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/res/anim/fade_in.xml
  android/app/src/main/res/anim/fade_out.xml
  android/app/src/main/res/drawable/ic_arrow_up_24.xml
  android/app/src/main/res/layout/activity_pokemon_list.xml
Labels: AN_UI 🎨, v1.2.0 🏷️

#484 [1.2.0/AN-FEAT, AN-UI] 포켓몬 스탯 프로그레스 바에 애니메이션 적용
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/stat/PokemonStatAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel2.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/ProgressBarAnimation.kt
  android/app/src/main/res/layout/item_stat.xml
  android/app/src/main/res/layout/item_type_result.xml
  android/app/src/main/res/values-ko-rKR/strings.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
Labels: AN_FEAT ✨, AN_UI 🎨, v1.2.0 🏷️

#487 [1.2.0/ AN-UI, AN-FEAT] 배틀 날씨 효과 UI 변경
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleBindingAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/WeatherUiModel.kt
  android/app/src/main/res/drawable/bg_battle_description.xml
  android/app/src/main/res/drawable/selector_button_clicked.xml
  android/app/src/main/res/layout-land/activity_battle.xml
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/item_spinner_weather.xml
  android/app/src/main/res/values-ko-rKR/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨, AN_UI 🎨, v1.2.0 🏷️
