Repository woowacourse-teams/2024-pokerogue-helper, pull requests merged in 2024-10, with the labels that each got.

#345 [1.1.0/AN-UI] 타입 아이콘 불일치 수정
  android/app/src/main/res/drawable/icon_type_dark.xml
  android/app/src/main/res/drawable/icon_type_fairy.xml
  android/app/src/main/res/drawable/icon_type_ice.xml
  android/app/src/main/res/drawable/icon_type_poison.png
  android/app/src/main/res/drawable/icon_type_poison.xml
  android/app/src/main/res/values/colors.xml
Labels: AN_UI 🎨, v1.1.0 🏷️

#343 [1.1.0/AN_FEAT] 배틀 구도 날씨 저장
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/view/WeatherItemSelectedListener.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
  android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt
Labels: AN_FEAT ✨, v1.1.0 🏷️

#355 [1.1.0/AN-FEAT] 룸 엔티티 수정 대응(destructive-recreation)
  android/local/src/main/java/poke/rogue/helper/local/dao/PokemonDao.kt
  android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt
Labels: AN_FEAT ✨, v1.1.0 🏷️

#350 [BE-INFRA] 서버별 CD 워크플로우 생성
  .github/workflows/Backend-CD-Prod-A.yml
  .github/workflows/Backend-CD-Prod-B.yml
Labels: BE_INFRA 🚧

#361 [1.1.0/AN-Refactor] Koin 기초 세팅, App, data, local, remote, testing, analytics 모듈 세팅
  android/analytics/build.gradle.kts
  android/analytics/src/main/java/poke/rogue/helper/analytics/di/AnalyticsModule.kt
  android/app/build.gradle.kts
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
  android/app/src/main/java/poke/rogue/helper/di/AppModule.kt
  android/app/src/main/java/poke/rogue/helper/di/ViewModelModule.kt
  android/app/src/main/java/poke/rogue/helper/presentation/base/toolbar/ToolbarActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/PokemonListActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/PokemonListViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/di/TestViewModelModule.kt
  android/data/build.gradle.kts
  android/data/src/main/java/poke/rogue/helper/data/di/CacheModule.kt
  android/data/src/main/java/poke/rogue/helper/data/di/DataModule.kt
  android/data/src/main/java/poke/rogue/helper/data/di/DataSourceModule.kt
  android/data/src/main/java/poke/rogue/helper/data/di/RepositoryModule.kt
  android/gradle/libs.versions.toml
  android/local/build.gradle.kts
  android/local/src/androidTest/java/poke/rogue/helper/local/dao/PokemonDaoTest.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/di/TestLocalModule.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/utils/KoinAndroidUnitTestRule.kt
  android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt
  android/local/src/main/java/poke/rogue/helper/local/di/DaoModule.kt
  android/local/src/main/java/poke/rogue/helper/local/di/DataBaseModule.kt
  android/local/src/main/java/poke/rogue/helper/local/di/DataStoreModule.kt
  android/local/src/main/java/poke/rogue/helper/local/di/LocalModule.kt
  android/remote/build.gradle.kts
  android/remote/src/main/java/poke/rogue/helper/remote/di/RemoteModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/di/RetrofitModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/di/ServiceModule.kt
  android/remote/src/test/java/poke/rogue/helper/remote/service/AbilityServiceTest.kt
  android/remote/src/test/java/poke/rogue/helper/remote/service/di/TestRemoteModule.kt
  android/testing/build.gradle.kts
  android/testing/src/main/java/poke/rogue/helper/testing/TestApplication.kt
  android/testing/src/main/java/poke/rogue/helper/testing/di/TestingModule.kt
  android/testing/src/main/java/poke/rogue/helper/testing/rule/KoinAndroidUnitTestRule.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepositoryTest.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeDexRepositoryTest.kt
  android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeTypeRepositoryTest.kt
Labels: AN_REFACTOR ✍️, v1.1.0 🏷️

#369 [1.1.1/AN-UI, AN-REFACTOR] 포켓몬 상세 화면 스크롤 시 애니메이션
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/EvolutionStageAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/EvolutionStageViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/EvolutionsUiModel.kt
  android/app/src/main/res/drawable/icon_type_fire.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_evolution.xml
  android/app/src/main/res/layout/fragment_pokemon_information.xml
  android/app/src/main/res/layout/fragment_pokemon_skills.xml
  android/app/src/main/res/layout/fragment_pokemon_stat.xml
  android/app/src/main/res/layout/view_group_pokemon_evolution.xml
Labels: AN_UI 🎨, AN_REFACTOR ✍️, v1.1.1 🏷️

#360 [BE-FEAT] 기술 관련 api 만들기
  .github/workflows/Backend-CI.yml
  backend/pokerogue/src/main/java/com/pokerogue/helper/data/PokemonValidator.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveTarget.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/dto/MoveDetailResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonRepository.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/repository/MoveRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/service/MoveServiceTest.java
Labels: BE_FEAT ✨

#363 [BE-REFACTOR] 바이옴 포켓몬 티어 정렬
  backend/pokerogue/src/main/java/com/pokerogue/PokerogueApplication.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/controller/BiomeController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/converter/SortingCriteriaRequestConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DataMongoDbConfig.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/WebConfig.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/constant/SortingCriteria.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java
  backend/pokerogue/src/test/java/com/pokerogue/environment/controller/ControllerTest.java
  backend/pokerogue/src/test/java/com/pokerogue/environment/repository/MongoRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/biome/controller/BiomeControllerTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/biome/service/BiomeServiceTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/biome/service/NativePokemonComparatorTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/global/constant/SortingCriteriaTest.java
Labels: BE_REFACTOR 🌿

#385 [1.1.0/AN-FEAT] Splash 화면에서 포켓몬 데이터 캐싱 교체 전략 추가
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/splash/PokemonIntroViewModel.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalVersionDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteVersionDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/di/DataSourceModule.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/dao/PokemonDaoTest.kt
  android/local/src/main/java/poke/rogue/helper/local/dao/PokemonDao.kt
  android/local/src/main/java/poke/rogue/helper/local/datastore/VersionDataStore.kt
  android/local/src/main/java/poke/rogue/helper/local/di/DataStoreModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/di/ServiceModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/dto/response/version/VersionResponse.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/ServiceModule.kt
  android/remote/src/main/java/poke/rogue/helper/remote/service/VersionService.kt
Labels: AN_FEAT ✨, v1.1.0 🏷️

#378 [1.1.1/AN-FEAT] 포켓몬 상세에서 배틀 도우미로 가는 floating 버튼 추가
  android/app/src/main/java/poke/rogue/helper/presentation/dex/AnalyticsExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/NavigateToBattleEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailNavigateHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/context/ContextExtension.kt
  android/app/src/main/res/anim/from_bottom.xml
  android/app/src/main/res/anim/rotate_close.xml
  android/app/src/main/res/anim/rotate_open.xml
  android/app/src/main/res/anim/to_bottom.xml
  android/app/src/main/res/drawable/ic_pokemon_battle_enemy.png
  android/app/src/main/res/drawable/ic_pokemon_battle_mine.png
  android/app/src/main/res/drawable/shape_red_20_fill_20_rect.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/values/dimensions.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨, v1.1.1 🏷️

#397 포켓몬 데이터 캐싱
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/repository/PokemonInMemoryRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
Labels: BE_FEAT ✨

#395 [1.1.0/AN-Config] Android CI/CD WorkFlow 최적화, 플레이스토어 자동 배포
  .github/workflows/Android_Develop_CD.yml
  .github/workflows/Android_Develop_CI.yml
  .github/workflows/Android_Release_CD.yml
  .github/workflows/Android_Release_CI.yml
Labels: AN_CONFIG 🧭, AN_CI/CD 🤖, v1.1.0 🏷️

#408 [1.1.0] Android release1.1.0 to an/develop
  .github/workflows/Android_Release_CD.yml
  .github/workflows/PR_Comment_Notification.yml
  README.md
  android/app/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: v1.1.1 🏷️

#413 [1.1.1/AN-FEAT] 포켓몬 상세에서 배틀 도우미로 가는 floating 버튼 추가(Revert 된 것 다시)
  android/app/src/main/java/poke/rogue/helper/presentation/dex/AnalyticsExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/NavigateToBattleEvent.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailNavigateHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/context/ContextExtension.kt
  android/app/src/main/res/anim/from_bottom.xml
  android/app/src/main/res/anim/rotate_close.xml
  android/app/src/main/res/anim/rotate_open.xml
  android/app/src/main/res/anim/to_bottom.xml
  android/app/src/main/res/drawable/ic_pokemon_battle_enemy.png
  android/app/src/main/res/drawable/ic_pokemon_battle_mine.png
  android/app/src/main/res/drawable/shape_red_20_fill_20_rect.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/values/dimensions.xml
  android/app/src/main/res/values/strings.xml
Labels: AN_FEAT ✨, AN_UI 🎨

#383 [1.1.1/AN-UI] 홈 화면 반응형 UI 구현하기
  android/app/src/main/res/layout-land/activity_home.xml
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/values-sw600dp/dimens.xml
  android/app/src/main/res/values/dimens.xml
Labels: AN_UI 🎨, v1.1.1 🏷️

#379 [1.1.1/AN-FEAT] 페이지 이동 로직 개선
  android/app/build.gradle.kts
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/SelectionType.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/res/drawable/icon_info.xml
  android/app/src/main/res/drawable/selector_toggle_btn.xml
  android/app/src/main/res/drawable/shape_toggle_thumb.xml
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/activity_biome_detail.xml
  android/app/src/main/res/values/strings.xml
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalNavigationDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/di/DataSourceModule.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BiomeRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/gradle/libs.versions.toml
  android/local/src/main/java/poke/rogue/helper/local/datastore/NavigationModeDataStore.kt
  android/local/src/main/java/poke/rogue/helper/local/di/DataStoreModule.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepository.kt
Labels: AN_FEAT ✨, v1.1.1 🏷️

#386 [1.1.1/AN-UI] 특성 화면 및 디테일 반응형 UI 구현하기
  android/app/src/main/res/layout-land/fragment_ability_detail.xml
  android/app/src/main/res/layout/fragment_ability_detail.xml
  android/app/src/main/res/layout/item_ability_description.xml
  android/app/src/main/res/values-sw600dp/dimens.xml
  android/app/src/main/res/values/dimens.xml
Labels: AN_UI 🎨, v1.1.1 🏷️

#415 [1.1.1/AN-REFACTOR] 타입, 배틀 화면 Koin 적용
  android/app/src/main/java/poke/rogue/helper/di/ViewModelModule.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
  android/app/src/test/java/poke/rogue/helper/presentation/battle/BattleActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/di/TestViewModelModule.kt
  android/app/src/test/java/poke/rogue/helper/presentation/type/TypeActivityTest.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBattleRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/di/TestingModule.kt
  android/testing/src/main/java/poke/rogue/helper/testing/rule/KoinAndroidUnitTestRule.kt
Labels: AN_REFACTOR ✍️, v1.1.1 🏷️

#418 [1.1.1/AN-UI, AN-FEAT] 배틀 가로 화면 대응 및 상세 페이지 이동 로직 추가
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleNavigationHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleSelectionsState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/BattlePokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionViewHolder.kt
  android/app/src/main/res/drawable/bg_battle_navigation_button.xml
  android/app/src/main/res/drawable/icon_book.xml
  android/app/src/main/res/layout-land/activity_battle.xml
  android/app/src/main/res/layout-land/activity_battle_selection.xml
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/values-sw600dp/type.xml
Labels: AN_FEAT ✨, AN_UI 🎨, v1.1.1 🏷️

#402 [1.1.1/AN-REFACTOR] 특성 및 홈 화면 의존성 Koin 적용
  android/app/build.gradle.kts
  android/app/src/main/java/poke/rogue/helper/di/ViewModelModule.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilityFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/home/HomeActivity.kt
  android/app/src/test/java/poke/rogue/helper/presentation/ability/AbilityActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/ability/AbilityFragmentTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/ability/AbilityViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailFragmentTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/di/TestViewModelModule.kt
  android/app/src/test/java/poke/rogue/helper/presentation/home/HomeActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/home/HomeViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
  android/gradle/libs.versions.toml
Labels: AN_REFACTOR ✍️, v1.1.1 🏷️

#425 [1.1.1/AN-REFACTOR] 바이옴(리스트,상세)화면 의존성 Koin 적용
  android/app/src/main/java/poke/rogue/helper/di/ViewModelModule.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailViewModel.kt
  android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/biome/detail/BiomeDetailActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/di/TestViewModelModule.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepository.kt
Labels: AN_REFACTOR ✍️, v1.1.1 🏷️

#414 [1.1.1/AN-REFACTOR] 포켓몬 상세, 인트로 부분 koin 적용
  android/app/build.gradle.kts
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
  android/app/src/main/java/poke/rogue/helper/di/ViewModelModule.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonInformationFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/skill/PokemonDetailSkillFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/stat/PokemonStatFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/splash/PokemonIntroActivity.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivityTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/evolution/PokemonEvolutionFragmentTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/information/PokemonInformationFragmentTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/skill/PokemonDetailSkillFragmentTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/stat/PokemonStatFragmentTest.kt
  android/app/src/test/java/poke/rogue/helper/presentation/di/TestViewModelModule.kt
  android/data/src/main/java/poke/rogue/helper/data/cache/GlideImageCacher.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalNavigationDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteBattleDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteBiomeDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteDexDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/utils/KoinAndroidUnitTestRule.kt
  android/local/src/main/java/poke/rogue/helper/local/dao/PokemonDao.kt
  android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt
  android/remote/src/main/java/poke/rogue/helper/remote/injector/ServiceModule.kt
Labels: AN_REFACTOR ✍️, v1.1.1 🏷️

#426 [1.1.1/AN-UI] 포켓몬 상세 화면 가로 화면 대응
  android/app/src/androidTest/java/poke/rogue/helper/presentation/home/HomeActivityTest.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonInformationFragment.kt
  android/app/src/main/res/layout-land/activity_pokemon_detail.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_evolution.xml
  android/app/src/main/res/layout/fragment_pokemon_information.xml
  android/app/src/main/res/layout/fragment_pokemon_skills.xml
  android/app/src/main/res/layout/fragment_pokemon_stat.xml
  android/app/src/main/res/layout/item_ability_title.xml
  android/app/src/main/res/layout/item_biome.xml
  android/app/src/main/res/layout/item_pokemon_detail_evolution.xml
  android/app/src/main/res/layout/item_pokemon_detail_information_biome.xml
  android/app/src/main/res/layout/item_pokemon_detail_skill.xml
  android/app/src/main/res/layout/item_stat.xml
  android/app/src/main/res/values-land/dimensions.xml
  android/app/src/main/res/values-sw600dp/dimens.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/dimensions.xml
  android/remote/src/main/java/poke/rogue/helper/remote/injector/RetrofitModule.kt
Labels: AN_UI 🎨, v1.1.1 🏷️

#435 [BE-INFRA] cd 워크플로우 트리거 이벤트 변경
  .github/workflows/Backend-CD-Prod-All.yml
Labels: BE_INFRA 🚧

#433 [1.1.1/AN-feat] PokemonList 화면에서 필터링, 정렬, 검색 시 Scroll 최상단으로 올리기
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListActivity.kt
Labels: AN_FEAT ✨, v1.1.1 🏷️

#434 [1.1.1/AN-feat] DB 마이그레이션 (Drop 방식 X)
  android/build.gradle.kts
  android/gradle/libs.versions.toml
  android/local/build.gradle.kts
  android/local/schemas/poke.rogue.helper.local.db.PokeRogueDatabase/1.json
  android/local/schemas/poke.rogue.helper.local.db.PokeRogueDatabase/2.json
  android/local/schemas/poke.rogue.helper.local.db.PokeRogueDatabase/3.json
  android/local/src/androidTest/java/poke/rogue/helper/local/database/PokeRogueDatabaseMigrationTest.kt
  android/local/src/androidTest/java/poke/rogue/helper/local/utils/MigrationTestUtils.kt
  android/local/src/main/java/poke/rogue/helper/local/db/PokeRogueDatabase.kt
  android/local/src/main/java/poke/rogue/helper/local/db/migrations/Migration1To2.kt
  android/local/src/main/java/poke/rogue/helper/local/di/DataBaseModule.kt
  android/local/src/main/java/poke/rogue/helper/local/entity/PokemonEntity.kt
Labels: AN_FEAT ✨, v1.1.1 🏷️

#438 [1.1.1-AN/UI,Fix] 포켓몬 formName 중복 적용 삭제, 포켓몬리스트 이름 MaxLine 1지정, 바이옴 Detail 에 포켓몬 없는 tier 필터링
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/BiomPokemonAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/boss/BiomeBossAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/gym/BiomeGymAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/wild/BiomeWildAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/model/BiomePokemonUiModel.kt
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/item_ability_detail_pokemon.xml
  android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
  android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/biome/BossPokemon.kt
  android/data/src/main/java/poke/rogue/helper/data/model/biome/WildPokemon.kt
Labels: AN_FIX 🐛, AN_UI 🎨, v1.1.1 🏷️
