Repository woowacourse-teams/2024-pokerogue-helper, pull requests merged in 2024-09, with the labels that each got.

#300 [1.1.0.alpha/AN-FIX] 바이옴 디테일 페이지 UI 수정
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/boss/BiomeBossFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/gym/BiomeGymFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/detail/wild/BiomeWildViewHolder.kt
  android/app/src/main/res/layout/fragment_biome_boss_pokemon.xml
  android/app/src/main/res/layout/fragment_biome_gym_pokemon.xml
  android/app/src/main/res/layout/item_biome_next_biomes.xml
  android/app/src/main/res/values/strings.xml
  android/local/src/androidTest/java/poke/rogue/helper/local/entity/PokemonFixtures.kt
Labels: AN_FIX 🐛, AN_UI 🎨

#303 [1.1.0-AN/Feat] id 기반으로 로그 심기 + 로그 이벤트 비동기 처리 AN_FEAT ✨
  android/analytics/src/main/java/poke/rogue/helper/analytics/AnalyticsScope.kt
  android/analytics/src/main/java/poke/rogue/helper/analytics/FireBaseAnalyticsLogger.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/AnalyticsExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SelectionData.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/AnalyticsExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/utils/AnalyticsExtensions.kt
Labels: AN_FEAT ✨

#306 [1.1.0/AN_FEAT,AN_UI] 바이옴 전체 지도 toolbar에 웹뷰 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeUiEventHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/guide/BiomeGuideActivity.kt
  android/app/src/main/res/drawable/ic_biome_map.xml
  android/app/src/main/res/layout/activity_biome.xml
  android/app/src/main/res/layout/activity_biome_detail.xml
  android/app/src/main/res/layout/activity_biome_guide.xml
  android/app/src/main/res/layout/item_biome_next_biomes.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeViewModelTest.kt
Labels: AN_FEAT ✨, AN_UI 🎨

#310 [1.1.0/AN_FIX] 배틀 디테일 로직 수정
  android/app/src/main/java/poke/rogue/helper/presentation/battle/AnalyticsExtensions.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleNavigationHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleSelectionUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SelectionData.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SelectionMode.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/SkillSelectionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/BattleSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/SelectionStep.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/BattlePokemonTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/filter/SelectableUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt
  android/app/src/main/java/poke/rogue/helper/presentation/util/view/ViewExtension.kt
  android/app/src/main/res/layout/activity_battle.xml
  android/app/src/main/res/layout/activity_battle_selection.xml
  android/app/src/main/res/layout/fragment_skill_selection.xml
Labels: AN_FIX 🐛

#308 [1.1.0.alpha/AN_FEAT, AN_UI] 도감 상세 UI 수정, 바이옴에서의 포켓몬 타입 가져오기
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailUiState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeTypesAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonDetailBiomeViewHolder.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/information/PokemonInformationFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/skill/PokemonDetailSkillFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/stat/PokemonStatFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/model/PokemonBiomeUiModel.kt
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/layout/fragment_pokemon_information.xml
  android/app/src/main/res/layout/item_pokemon_detail_information_biome.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonBiome.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
Labels: AN_FEAT ✨, AN_UI 🎨

#290 [1.1.0/AN_CD] Discord로 alpha 버전 apk 전달
  .github/actions/add_labels/action.yml
  .github/workflows/Android_Develop_PR_Builder.yml
  .github/workflows/Android_PR_AUTO_ASSIGN.yml
  .github/workflows/Android_PR_Builder.yml
Labels: AN_CI/CD 🤖, v1.1.0 🏷️

#321 [1.1.0/AN_CI] develop PR Ci, CD 분리
  .github/workflows/Android_Develop_PR_CD.yml
Labels: AN_CI/CD 🤖, v1.1.0 🏷️

#316 [1.1.0/AN-FEAT] 배틀 선택 / 결과 UI 개선
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/model/BattlePredictionUiModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/pokemon/PokemonSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionViewModel.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/RemoteBattleDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
Labels: AN_FEAT ✨, AN_UI 🎨

#318 [1.1.0/AN_REFACTOR] APP 단의 FIrebase 초기화 코드 analytics 모듈로 이동
  android/analytics/src/main/java/poke/rogue/helper/analytics/AnalyticsInitializer.kt
  android/analytics/src/main/java/poke/rogue/helper/analytics/AnalyticsLogger.kt
  android/app/src/main/java/poke/rogue/helper/PokeRogueHelperApp.kt
Labels: AN_REFACTOR ✍️

#325 [BE-INFRA] 개발, 배포 Github Actions 워크플로우 분리
  .github/workflows/Backend-CD-Dev.yml
  .github/workflows/Backend-CD-Infra.yml
  .github/workflows/Backend-CD-Prod.yml
Labels: BE_INFRA 🚧

#320 [1.1.0/AN_FEAT] 바이옴 리스트 검색 기능 구현
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeQueryHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeSearchViewBindingAdapter.kt
  android/app/src/main/java/poke/rogue/helper/presentation/biome/BiomeViewModel.kt
  android/app/src/main/res/layout/activity_biome.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/poke/rogue/helper/presentation/biome/BiomeViewModelTest.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BiomeRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBiomeRepository.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeBiomeRepository.kt
Labels: AN_FEAT ✨

#334 [BE-TEST] MongoRepository 뼈대 테스트 코드 추가
  backend/pokerogue/src/test/java/com/pokerogue/environment/repository/MongoRepositoryTest.java
Labels: BE_TEST 🧪

#324 [1.1.0/AN_FEAT] 배틀 선택 데이터 저장
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleSelectionsState.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
  android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt
  android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
  android/data/src/main/java/poke/rogue/helper/data/model/PokemonWithSkillIds.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/BattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DefaultDexRepository.kt
  android/data/src/main/java/poke/rogue/helper/data/repository/DexRepository.kt
  android/gradle/libs.versions.toml
  android/local/build.gradle.kts
  android/local/src/main/java/poke/rogue/helper/local/datastore/.gitkeep
  android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt
  android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeDexRepository.kt
Labels: AN_FEAT ✨, v1.1.0 🏷️

#327 [1.1.0-AN-CI/CD] WorkFlow PR CI 2번 돌아가는거 수정, CI/CD actions 파일로 분리
  .github/actions/ktlint_check/action.yml
  .github/actions/unit_test/action.yml
  .github/workflows/Android_Develop_PR_Builder.yml
  .github/workflows/Android_Develop_PR_CD.yml
  .github/workflows/Android_Develop_PR_CI.yml
Labels: AN_CI/CD 🤖, v1.1.0 🏷️

#341 [BE-REFACTOR] MongoDB를 사용하여 Type을 연결하고 코드를 개선
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/DataInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/InMemoryTypeMatchingRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/battle/MoveCategory.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/converter/TierConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Biome.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NextBiome.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Trainer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/ConverterConfig.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/MoveRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/converter/FlagConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/converter/MoveCategoryConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/converter/MoveTargetConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/Move.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveTarget.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/PokemonDatabaseInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/converter/EvolutionItemConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/Evolution.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/EvolutionItem.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/FormChange.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/Pokemon.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/collection/TypeMatching.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/controller/PokemonTypeController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/converter/TypeReadConverter.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/data/Type.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeMatchingResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/PokemonTypeResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/dto/TypeMatchingResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/repository/TypeMatchingRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
  backend/pokerogue/src/test/java/com/pokerogue/environment/repository/MongoRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/battle/DataInitializerTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/battle/MoveCategoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/biome/converter/TierConverterTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/biome/data/TierTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/converter/FlagConverterTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/converter/MoveCategoryConverterTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/converter/MoveTargetConverterTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/data/MoveFlagTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/data/MoveTargetTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/move/repository/MoveRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/converter/EvolutionItemConverterTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/EvolutionItemTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/repository/PokemonRepositoryTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/type/converter/TypeReadConverterTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/type/data/TypeTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/type/repository/TypeMatchingRepositoryTest.java
Labels: BE_REFACTOR 🌿

#349 [BE-REFACTOR] Ability 정보 MongoDB 사용하도록 리팩토링
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/AbilityController.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/data/Ability.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/data/AbilityInfo.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/AbilityDetailResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/AbilityPokemonResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/AbilityResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/AbilityTypeResponse.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/InMemoryAbilityRepository.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/AbilityService.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/PokemonDatabaseInitializer.java
  backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/AbilityServiceTest.java
  backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/InMemoryPokemonDatabaseInitializerTest.java
Labels: BE_REFACTOR 🌿
