Repository woowacourse-teams/2024-pokerogue-helper, pull requests merged in 2025-04, with the labels that each got.

#494 [1.2.1/ AN-CONFIG] :stringmatcher java 설정 변경
  android/stringmatcher/build.gradle.kts
Labels: AN_CONFIG 🧭, v1.2.1 🏷️

#491 [1.2.1/ AN-FIX] 포켓몬 상세 > 정보 탭 > 바이옴 이미지 확장되는 문제 수정
  android/app/src/main/res/layout/activity_biome.xml
  android/app/src/main/res/layout/item_biome.xml
  android/app/src/main/res/layout/item_pokemon_detail_information_biome.xml
  android/app/src/main/res/values/dimens.xml
Labels: AN_FIX 🐛, v1.2.1 🏷️

#500 [1.2.1/AN-Fix] 포켓몬 폼 형태 이름 중복해서 보이는 문제 해결
  android/data/src/main/java/poke/rogue/helper/data/model/Pokemon.kt
Labels: AN_FIX 🐛, v1.2.1 🏷️

#497 [1.2.1/ AN-FEAT] 포켓몬 상세 스크롤 시 포켓몬 이미지와 타입이 상단으로 이동하는 애니메이션
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailNavigateHandler.kt
  android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
  android/app/src/main/java/poke/rogue/helper/ui/component/PokeChip.kt
  android/app/src/main/java/poke/rogue/helper/ui/layout/PaddingValues.kt
  android/app/src/main/res/layout-land/activity_pokemon_detail.xml
  android/app/src/main/res/layout/activity_pokemon_detail.xml
  android/app/src/main/res/values-land/dimensions.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/xml/activity_pokemon_detail_motion_layout_scene.xml
Labels: AN_FEAT ✨, v1.2.1 🏷️
